### ISSUE TITLE
"Create Station" not working 

### ISSUE THREAD

**Issue by tnier01** [Birdiary/webserver#24]
If you want to create a station via https://www.wiediversistmeingarten.org/view/createstation no station is created. No matter if an email is inserted or not. At least this is the case for me with firefox 

<img width="1789" alt="Bildschirmfoto 2022-09-09 um 18 06 00" src="https://user-images.githubusercontent.com/46532733/189393604-bff22c4b-8720-4667-a780-2970e2731d35.png">

- [x] fix create station 
- [x] is it needed that the create station object is shown?
- [x] related to item before: needed to show the array of all stations in the console?

**Comment by NJaku01** [comment]
@tnier01 can you check again if this is now fixed?

**Comment by tnier01** [comment]
@NJaku01 seems to be fixed, was able to create a new station. Whats about the two other mentioned tasks?

**Comment by NJaku01** [comment]
@tnier01 
The other two points are not fixed yet. Do zu just mean they they are not printed in the console?
