### ISSUE TITLE
url fallback 

### ISSUE THREAD

**Issue by tnier01** [Birdiary/webserver#35]
If the discrete url to a station is not working e.g. [https://www.wiediversistmeingarten.org/view/station/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx](https://www.wiediversistmeingarten.org/view/station/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx) then not the station page of a station that does not exist should be shown, but the overview map [https://www.wiediversistmeingarten.org/view/](https://www.wiediversistmeingarten.org/view/)

now: 
![Bildschirmfoto 2022-10-26 um 11 11 05](https://user-images.githubusercontent.com/46532733/197985568-39210984-cf95-4363-9d97-e1847ec5d171.png)

**Comment by NJaku01** [comment]
Information text still looks a little bit messy
