### ISSUE TITLE
white space in view + Leaflet credentials not viewable 

### ISSUE THREAD

**Issue by tnier01** [Birdiary/webserver#38]
On the left side there is a vertically white bar. Additionally the Leaftlet credentials are sometimes not visible at all or only partially visible. Have a look at the screenshot below and the red marked rectangles. 

<img width="1792" alt="Bildschirmfoto 2022-10-27 um 11 54 52" src="https://user-images.githubusercontent.com/46532733/198254276-57040b98-dd4e-4378-b724-45be93724a2a.png">

**Comment by NJaku01** [comment]
Fixed with b752bacc0212a3ae6faf4cfceac0e499066f17a8
