### ISSUE TITLE
Add Environment silolevel to the API & Database

### ISSUE THREAD

**Issue by Andeicon** [Birdiary/webserver#52]
In order to get the actually amount of Bird-food in the silo and have a chance to be notified if the Silo in empty, a Distance sensor is added via a VL53XX to the station. This especially useful for public stations.
This _"Silolevel"_ in percent should be possible to be send to the API.
For backward compatibility the value should be optional in the API. Also the Value is not really a Environment Value. Maybe a additional Section could make sense.

**Comment by njakuschona** [comment]
There is now an endpoint /api/feed which allows to POST and GET information about the feeder.  The important fact it should contian is the date and the silolevel. The silolevel is also displayed on the webiste. Further information can be added to the JSON like fodderType but are not displayed on the website. Currently there is also just the displaying of the last silolevel send, in the database alle silolevels are saved. An request can look like this
```
payload = {
       "date": "2022-11-16 16:20:10.210804",
        "silolevel": 80
    }
r = requests.post("https://wiediversistmeingarten.org" +"/api/feed/" + "24943bb4-b902-4b32-9262-f79ecd9d69c7", json=payload)
```

**Comment by njakuschona** [comment]
`TODO: Update Documentation
