### ISSUE TITLE
Add Environment Values air-pressure and illuminance to the API & Database

### ISSUE THREAD

**Issue by Andeicon** [Birdiary/webserver#53]
in addition to #52 it would be useful to add additional values to the API. I have prepared a modification to use a BME280 as Temperature and humidity Sensor that also provides the air-pressure.
Also I have added A BH1750 wich messures the illumance.
For backward compatibility the value should be optional in the API.

**Comment by njakuschona** [comment]
It is now possible to add more environmental measurements in the JSON. All types of measurements can be added in the payload. However, it is important that in each object are the collected data. So temperature and humidity are included. The variables "airpressure" and "illuminance" are now also displayed on the website.
A request can look like this:
```
payload = {
       "date": "2022-11-16 16:20:10.210804",
        "temperature": 22,
        "humidity": 80,
        "airpressure": 1203,
        "illuminance": 20
    }
       
r = requests.post("https://wiediversistmeingarten.org" +"/api/environment/" + "<station_id>", json=payload)
```
