### ISSUE TITLE
api exited with code 1

### ISSUE THREAD

**Issue by DieterPN** [Birdiary/webserver#54]
Hi,
I tried to install the webserver with "docker-compose --file docker-compose-dev.yml up" on Windows 10 with WSL2 and Docker Desktop.

Attached is the printout during installation process:
[output during installation.txt](https://github.com/Birdiary/webserver/files/12336578/output.during.installation.txt)
 
Several errors and warnings - any hint what went wrong is welcome.

Thank You

Dieter

**Comment by njakuschona** [comment]
Hello Dieter,

this was a fault in our code. I just forgot to push the newest version to GitHub. Now you can pull and try it again. To force Docker to rebuild the images we suggest this command "docker-compose --file docker-compose-dev.yml up --build".

In general we would be happy if you give us some information about what you plan to do with your own server. Then we can also give more precise tips on how to configure it.

Best Nick
